import datetime
from ollama import chat, ChatResponse

# --- TOOLS: responses Dr. Mio sends back to incoming emails ---

def homework_submission(student_name: str):
  """Reply confirming submission received"""
  return f"""Subject: Re: Homework Submission

Dear {student_name},

Thank you for your submission. I confirm that your homework has been successfully received on {datetime.datetime.today().strftime('%Y-%m-%d %H:%M')}.

Best regards,
Dr. Mio
"""


def ask_exam_date(student_name: str):
  """Reply to student asking about exam date"""
  return f"""Subject: Re: Exam Date Inquiry

Dear {student_name},

Thank you for your message. The exam date will be announced soon. Please keep an eye on the course updates.

Best regards,
Dr. Mio
"""


def exam_review_request(student_name: str):
  """Reply to exam review request"""
  return f"""Subject: Re: Exam Review Request

Dear {student_name},

Thank you for your request. I will review your exam and get back to you shortly with further details.

Best regards,
Dr. Mio
"""


def colleague_meeting(colleague_name: str):
  """Reply to meeting request"""
  return f"""Subject: Re: Meeting Request

Dear {colleague_name},

Thank you for reaching out. I would be happy to meet. Please let me know your availability so we can schedule a suitable time.

Best regards,
Dr. Mio
"""


def be_back_soon(sender_name: str):
  """If the request in received mail can't be categorized, use the  Quick auto-reply (away message) tool"""
  return f"""Subject: Re: Message Received

Dear {sender_name},

Thank you for your message. I am currently unavailable but will get back to you as soon as possible.

Best regards,
Dr. Mio
"""


# Map tool names to functions
available_functions = {
  'homework_submission': homework_submission,
  'ask_exam_date': ask_exam_date,
  'exam_review_request': exam_review_request,
  'colleague_meeting': colleague_meeting,
  'be_back_soon': be_back_soon,
}

# Example incoming email
messages = [
  {
    'role': 'system',
    'content': """You are an AI agent that reads and categorizes incoming emails for Dr. Mio, a university professor.

Your tasks:
1. Carefully read the incoming email.
2. Identify the intent/category of the email (e.g., homework submission, exam date inquiry, exam review request, meeting request, general message).
3. Select and call the most appropriate available tool to generate a response.

Rules:
- Do NOT write email responses yourself.
- You MUST use the provided tools to generate all replies.
- Choose the tool that best matches the email’s intent.
- Pass the correct sender name as an argument to the tool.
- If the category is unclear, choose the closest matching tool.

Output requirements:
- Output ONLY the final response email generated by the tool.
- Do NOT include explanations, reasoning, or extra text.
- Do NOT include tool call details in the final answer.
"""
  },

  # Then the actual incoming email
  {
    'role': 'user',
    'content': """Dear Dr.Mio, 
    I hope you are doing well. My name is Alien, and I am a student in your course.

    I would like to kindly ask for reviewing of my exam result.

    Thank you very much for your time and assistance.

    Best regards,
    Alien
    """
  }
]

result :str = ""
# --- Tool loop ---
while True:
  response: ChatResponse = chat(
    model='gpt-oss',
    messages=messages,
    tools=list(available_functions.values()),
    think=True,
  )

  messages.append(response.message)
  # print("Thinking:", response.message.thinking)
  # print("Content:", response.message.content)

  if response.message.tool_calls:
    for tc in response.message.tool_calls:
      if tc.function.name in available_functions:
        # print(f"Calling {tc.function.name} with arguments {tc.function.arguments}")

        result = available_functions[tc.function.name](**tc.function.arguments)

        # print("Result:", result)

        messages.append({
          'role': 'tool',
          'tool_name': tc.function.name,
          'content': result
        })
  else:
    _, _, rest = result.partition("Subject:")

    subject_line, _, body = rest.strip().partition("\n")

    subject = subject_line.strip()
    content = body.strip()
    print({"Email": {
      "subject": subject,
      "content": content
    }})
    break
    